# mr.Tmux:

# Prefix
set -g prefix M-j
unbind C-b

# General
set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on
set -g escape-time 10
set -g history-limit 10000
set -g allow-rename off

# Colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Status bar
set -g status on
set -g status-justify centre
set -g status-left "#[fg=cyan]"
set -g status-right "#[fg=cyan]"

# Bindings
bind l last-window
# bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind v copy-mode
# bind space copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
# bind p paste-buffer
